export const userProfile = {
  nombre: "Iván Bongiovanni",
  titulo: "Desarrollador de Software",
  experiencia: [
    {
      empresa: "Tensolite SA",
      puesto: "Desarrollador Frontend",
      duracion: "4 meses",
      tecnologias: [
        "Desarrollo de aplicaciones web",
        "React-Redux",
        "TypeScript",
        "Redux-Toolkit",
        "JavaScript",
        "Desarrollo Full Stack",
        "React.js",
        "Codificación de front-end",
        "Mongoose",
        "React",
        "Node.js",
        "Express",
        "Laravel",
      ],
    },
    {
      empresa: "Doctor Qali",
      puesto: "Desarrollador Frontend",
      duracion: "4 meses",
      tecnologias: [
        "Desarrollo de aplicaciones web",
        "Prime react",
        "React-Redux",
        "Git",
        "TailwindCSS",
        "Redux-Toolkit",
        "Desarrollo Full Stack",
        "Desarrollo web",
        "Codificación de front-end",
        "GitHub",
        "Trabajo en equipo",
        "React",
      ],
    },
  ],
  educacion: {
    titulo: "Programador Universitario",
    institucion:
      "FACET - Facultad de Ciencias Exactas y Tecnologías de la Universidad Nacional de Tucumán",
    graduacion: "En curso",
  },
  habilidades: [
    "Desarrollador Front End",
    "React js",
    "Next js",
    "Astro",
    "JavaScript",
    "TypeScript",
    "Tailwind CSS",
    "Node.Js",
    "PrismaORM",
    "PostgreSQL",
    "Docker",
    "PHP",
  ],
  ubicacion: "Tucumán, Argentina",
  nivelIngles: "A1",
  expectativas: {
    tipoTrabajo: ["Remoto", "Híbrido"],
    salarioMinimo: 700000,
    modalidad: [
      "Tiempo Completo",
      "Freelance",
      "Proyecto",
      "Part Time",
      "Jornada Parcial",
      "Jornada Completa",
    ],
  },
};
